### ISSUE TITLE
Error initializing database setup from extension

### ISSUE THREAD

**Issue by dfelinto** [armadillica/pillar#1]
If I try to initialize the database from a pillar extension:
`python manage.py setup setup_db dfelinto+dillo@gmail.com`

I'm getting the following error:
```
 File "pillar/pillar/api/utils/authorization.py", line 313, in wrapper
    if require_cap and not g.current_user.has_cap(require_cap):
AttributeError: 'dict' object has no attribute 'has_cap''
```

The issue seems to be that _//pillar/cli/setup.py::setup_db()_ is initializing g.current_user as a dict instead of the expected class.

**Comment by sybrenstuvel** [comment]
Fixed in 86e76aaa5fb25b3ba2cf24de970dda95ece1b67b
